/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Congdan;

import view.congan.*;
import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class DBCongdan extends javax.swing.JFrame {

    /**
     * Creates new form DBCongan
     */
    Color DefaultColor,ClickedColor;
    public void disposeDB(){
        this.dispose();
    }
    public DBCongdan() {
        initComponents();
        DefaultColor =new Color(255,255,255);
        ClickedColor =new Color(102,204,255);
        
        //set default color to pan on run time
        labelCD.setBackground(DefaultColor);
        labelBS.setBackground(DefaultColor);
        labelType.setBackground(DefaultColor);
        labelLS.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        congDan = new javax.swing.JPanel();
        labelCD = new javax.swing.JLabel();
        bienSo = new javax.swing.JPanel();
        labelBS = new javax.swing.JLabel();
        loaiXe = new javax.swing.JPanel();
        labelType = new javax.swing.JLabel();
        lichSu = new javax.swing.JPanel();
        labelLS = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        DTPane = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        addCongdan = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý biển số xe");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setText("Xin chào, Minh Nhân");

        jLabel14.setText("Ngày mới tốt lành");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/quoc_huy.png"))); // NOI18N

        congDan.setBackground(new java.awt.Color(255, 255, 255));

        labelCD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user_group_30px.png"))); // NOI18N
        labelCD.setText("Công dân");
        labelCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelCDMousePressed(evt);
            }
        });

        javax.swing.GroupLayout congDanLayout = new javax.swing.GroupLayout(congDan);
        congDan.setLayout(congDanLayout);
        congDanLayout.setHorizontalGroup(
            congDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congDanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCD)
                .addGap(22, 22, 22))
        );
        congDanLayout.setVerticalGroup(
            congDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congDanLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelCD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bienSo.setBackground(new java.awt.Color(255, 255, 255));

        labelBS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelBS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/data_24px.png"))); // NOI18N
        labelBS.setText("Biển số xe ô tô");
        labelBS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBSMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelBSMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bienSoLayout = new javax.swing.GroupLayout(bienSo);
        bienSo.setLayout(bienSoLayout);
        bienSoLayout.setHorizontalGroup(
            bienSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bienSoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBS)
                .addGap(10, 10, 10))
        );
        bienSoLayout.setVerticalGroup(
            bienSoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bienSoLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelBS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loaiXe.setBackground(new java.awt.Color(255, 255, 255));

        labelType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/car (1).png"))); // NOI18N
        labelType.setText("Loại xe ô tô");
        labelType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTypeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelTypeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout loaiXeLayout = new javax.swing.GroupLayout(loaiXe);
        loaiXe.setLayout(loaiXeLayout);
        loaiXeLayout.setHorizontalGroup(
            loaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loaiXeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelType)
                .addGap(10, 10, 10))
        );
        loaiXeLayout.setVerticalGroup(
            loaiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loaiXeLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelType)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lichSu.setBackground(new java.awt.Color(255, 255, 255));

        labelLS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/history (1).png"))); // NOI18N
        labelLS.setText("Lịch sử tạo biển");
        labelLS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLSMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelLSMousePressed(evt);
            }
        });

        javax.swing.GroupLayout lichSuLayout = new javax.swing.GroupLayout(lichSu);
        lichSu.setLayout(lichSuLayout);
        lichSuLayout.setHorizontalGroup(
            lichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lichSuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLS)
                .addGap(10, 10, 10))
        );
        lichSuLayout.setVerticalGroup(
            lichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lichSuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelLS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lichSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(congDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(congDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lichSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jLabel17.setText("Trung úy");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel16.setText("Nguyễn Minh Nhân");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user (1).png"))); // NOI18N
        jLabel27.setText("jLabel14");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("Công dân");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search_40px.png"))); // NOI18N

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        addCongdan.setBackground(new java.awt.Color(51, 153, 255));
        addCongdan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addCongdan.setForeground(new java.awt.Color(255, 255, 255));
        addCongdan.setText("Thêm    +");
        addCongdan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCongdanMouseClicked(evt);
            }
        });
        addCongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCongdanActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow-down-sign-to-navigate (1).png"))); // NOI18N
        jButton11.setText("Sắp xếp");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/filter (1).png"))); // NOI18N
        jButton12.setText("Lọc");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CCCD", "Họ", "Tên", "Giới", "Ngày sinh", "Số điện thoại", "Địa chỉ"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        DTPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DTPane.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DTPane.setLayer(jTextField6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DTPane.setLayer(addCongdan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DTPane.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DTPane.setLayer(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DTPane.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DTPaneLayout = new javax.swing.GroupLayout(DTPane);
        DTPane.setLayout(DTPaneLayout);
        DTPaneLayout.setHorizontalGroup(
            DTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DTPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(DTPaneLayout.createSequentialGroup()
                        .addGroup(DTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DTPaneLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addCongdan)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DTPaneLayout.setVerticalGroup(
            DTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DTPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(DTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCongdan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 519, Short.MAX_VALUE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(22, 22, 22))
                    .addComponent(DTPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DTPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void addCongdanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCongdanMouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_addCongdanMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void addCongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCongdanActionPerformed
        // TODO add your handling code here:
        new ThemCongdan().setVisible(true);      
    }//GEN-LAST:event_addCongdanActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        new UserInfo().setVisible(true);       
    }//GEN-LAST:event_jLabel16MouseClicked

    private void labelCDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCDMousePressed
        // TODO add your handling code here:
        congDan.setBackground(ClickedColor);
        bienSo.setBackground(DefaultColor);
        loaiXe.setBackground(DefaultColor);
        lichSu.setBackground(DefaultColor);
    }//GEN-LAST:event_labelCDMousePressed

    private void labelBSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBSMousePressed
        // TODO add your handling code here:
        congDan.setBackground(DefaultColor);
        bienSo.setBackground(ClickedColor);
        loaiXe.setBackground(DefaultColor);
        lichSu.setBackground(DefaultColor);
    }//GEN-LAST:event_labelBSMousePressed

    private void labelTypeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTypeMousePressed
        // TODO add your handling code here:
        congDan.setBackground(DefaultColor);
        bienSo.setBackground(DefaultColor);
        loaiXe.setBackground(ClickedColor);
        lichSu.setBackground(DefaultColor);
    }//GEN-LAST:event_labelTypeMousePressed

    private void labelLSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLSMousePressed
        // TODO add your handling code here:
        congDan.setBackground(DefaultColor);
        bienSo.setBackground(DefaultColor);
        loaiXe.setBackground(DefaultColor);
        lichSu.setBackground(ClickedColor);
    }//GEN-LAST:event_labelLSMousePressed

    private void labelCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCDMouseClicked
        // TODO add your handling code here:
        MenuCongdan congDan = new MenuCongdan();
        DTPane.add(congDan).setVisible(true);
    }//GEN-LAST:event_labelCDMouseClicked

    private void labelBSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBSMouseClicked
        // TODO add your handling code here:
        MenuBienso bienSo = new MenuBienso();
        DTPane.add(bienSo).setVisible(true);
    }//GEN-LAST:event_labelBSMouseClicked

    private void labelTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTypeMouseClicked
        // TODO add your handling code here:
        MenuLoaixe loaiXe = new MenuLoaixe();
        DTPane.add(loaiXe).setVisible(true);
    }//GEN-LAST:event_labelTypeMouseClicked

    private void labelLSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLSMouseClicked
        // TODO add your handling code here:
        MenuLichsu lichSu = new MenuLichsu();
        DTPane.add(lichSu).setVisible(true);
    }//GEN-LAST:event_labelLSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBCongdan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBCongdan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBCongdan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBCongdan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBCongdan().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DTPane;
    private javax.swing.JButton addCongdan;
    private javax.swing.JPanel bienSo;
    private javax.swing.JPanel congAn1;
    private javax.swing.JPanel congDan;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel khuVuc3;
    private javax.swing.JLabel labelBS;
    private javax.swing.JLabel labelCD;
    private javax.swing.JLabel labelLS;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel lableCA;
    private javax.swing.JLabel lableCA6;
    private javax.swing.JPanel lichSu;
    private javax.swing.JPanel loaiXe;
    // End of variables declaration//GEN-END:variables
}
