/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.congan;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import view.Congdan.UserInfo;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import model.CongAn;
import view.Login;

/**
 *
 * @author LENOVO
 */
public class DBCongan extends javax.swing.JFrame {
    CongAn ongCan;
    MenuCongan menuCongan = new MenuCongan();
    MenuDonvi menuDonvi = new MenuDonvi();
    MenuKhuvuc menuKhuvuc = new MenuKhuvuc();

    /**
     * Creates new form DBCongan
     */
    Color DefaultColor,ClickedColor;
    public void disposeDB(){
        this.dispose();
    }
    public DBCongan() {
        initComponents();
        setIcon();
        DTPane.add(menuCongan).setVisible(true);
        DTPane.add(menuDonvi).setVisible(true);
        DTPane.add(menuKhuvuc).setVisible(true);
        this.setlocationrelativeto(null);
        
    }
    
    public DBCongan(CongAn ongCan){
        this.ongCan = ongCan;
        initComponents();
        setIcon();
        
        start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        congAn = new javax.swing.JPanel();
        lableCA = new javax.swing.JLabel();
        donVi = new javax.swing.JPanel();
        lableDV = new javax.swing.JLabel();
        khuVuc = new javax.swing.JPanel();
        lableKV = new javax.swing.JLabel();
        lableLogout = new javax.swing.JLabel();
        labelDarkmode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        DTPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý biển số xe");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        congAn.setBackground(new java.awt.Color(255, 255, 255));

        lableCA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lableCA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/police_32px.png"))); // NOI18N
        lableCA.setText("Công an");
        lableCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableCAMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lableCAMousePressed(evt);
            }
        });

        javax.swing.GroupLayout congAnLayout = new javax.swing.GroupLayout(congAn);
        congAn.setLayout(congAnLayout);
        congAnLayout.setHorizontalGroup(
            congAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congAnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableCA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        congAnLayout.setVerticalGroup(
            congAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, congAnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lableCA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        donVi.setBackground(new java.awt.Color(255, 255, 255));

        lableDV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lableDV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/police_station_26px.png"))); // NOI18N
        lableDV.setText(" Đơn vị");
        lableDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableDVMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lableDVMousePressed(evt);
            }
        });

        javax.swing.GroupLayout donViLayout = new javax.swing.GroupLayout(donVi);
        donVi.setLayout(donViLayout);
        donViLayout.setHorizontalGroup(
            donViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donViLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableDV)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        donViLayout.setVerticalGroup(
            donViLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donViLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lableDV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        khuVuc.setBackground(new java.awt.Color(255, 255, 255));

        lableKV.setBackground(new java.awt.Color(255, 255, 255));
        lableKV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lableKV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lableKV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/map_marker_30px.png"))); // NOI18N
        lableKV.setText("Khu vực");
        lableKV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableKVMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lableKVMousePressed(evt);
            }
        });

        javax.swing.GroupLayout khuVucLayout = new javax.swing.GroupLayout(khuVuc);
        khuVuc.setLayout(khuVucLayout);
        khuVucLayout.setHorizontalGroup(
            khuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khuVucLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lableKV, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        khuVucLayout.setVerticalGroup(
            khuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khuVucLayout.createSequentialGroup()
                .addComponent(lableKV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lableLogout.setBackground(new java.awt.Color(255, 255, 255));
        lableLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lableLogout.setText("Logout");
        lableLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableLogoutMouseClicked(evt);
            }
        });

        labelDarkmode.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelDarkmode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDarkmode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/darkmode.png"))); // NOI18N
        labelDarkmode.setText("Dark mode");
        labelDarkmode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDarkmodeMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vnuk100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDarkmode, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(khuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(congAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lableLogout))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(congAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(donVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(khuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(labelDarkmode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(lableLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel13.setText("Xin chào, Minh Nhân");

        jLabel14.setText("Ngày mới tốt lành");

        jLabel17.setText("Trung úy");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel16.setText("Nguyễn Minh Nhân");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user (1).png"))); // NOI18N
        jLabel27.setText("jLabel14");

        javax.swing.GroupLayout DTPaneLayout = new javax.swing.GroupLayout(DTPane);
        DTPane.setLayout(DTPaneLayout);
        DTPaneLayout.setHorizontalGroup(
            DTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        DTPaneLayout.setVerticalGroup(
            DTPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 541, Short.MAX_VALUE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DTPane)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DTPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lableKVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableKVMousePressed
        // TODO add your handling code here:
        congAn.setBackground(DefaultColor);
        donVi.setBackground(DefaultColor);
        khuVuc.setBackground(ClickedColor);
    }//GEN-LAST:event_lableKVMousePressed

    private void lableCAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableCAMousePressed
        // TODO add your handling code here:
        congAn.setBackground(ClickedColor);
        donVi.setBackground(DefaultColor);
        khuVuc.setBackground(DefaultColor);
    }//GEN-LAST:event_lableCAMousePressed

    private void lableDVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableDVMousePressed
        // TODO add your handling code here:
        congAn.setBackground(DefaultColor);
        donVi.setBackground(ClickedColor);
        khuVuc.setBackground(DefaultColor);
    }//GEN-LAST:event_lableDVMousePressed

    private void lableCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableCAMouseClicked
        // TODO add your handling code here:
        DTPane.setSelectedFrame(menuCongan);
        menuCongan.setVisible(true);
        menuDonvi.setVisible(false);
        menuKhuvuc.setVisible(false);
        menuCongan.start();
    }//GEN-LAST:event_lableCAMouseClicked

    private void lableDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableDVMouseClicked
        // TODO add your handling code here:
        DTPane.setSelectedFrame(menuDonvi);
        menuCongan.setVisible(false);
        menuDonvi.setVisible(true);
        menuKhuvuc.setVisible(false);
        menuDonvi.start();
    }//GEN-LAST:event_lableDVMouseClicked

    private void lableKVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableKVMouseClicked
        // TODO add your handling code here:
        DTPane.setSelectedFrame(menuKhuvuc);
        menuCongan.setVisible(false);
        menuDonvi.setVisible(false);
        menuKhuvuc.setVisible(true);
        menuKhuvuc.start();
    }//GEN-LAST:event_lableKVMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        new UserInfo(ongCan).setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void lableLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableLogoutMouseClicked
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_lableLogoutMouseClicked

    private void labelDarkmodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDarkmodeMouseClicked
        // TODO add your handling code here:
        try {
            if (UIManager.getLookAndFeel().getClass().getName().equals("com.formdev.flatlaf.FlatDarkLaf")) {
                UIManager.setLookAndFeel(new FlatLightLaf());
                labelDarkmode.setText("Dark mode");
                jPanel1.setBackground(new Color(255, 255, 255));
            } else {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                labelDarkmode.setText("Light mode");
                jPanel1.setBackground(new Color(99, 99, 99));
            }
            SwingUtilities.updateComponentTreeUI(this); // Update UI components
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
    }//GEN-LAST:event_labelDarkmodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBCongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBCongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBCongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBCongan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBCongan().setVisible(true);
                
            }
        });
    }
    
    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/assets/vnukmini.png")));
    }
    
    private void start() {
        DefaultColor =new Color(255,255,255);
        ClickedColor =new Color(102,204,255);
        
        // set default hello text
        jLabel13.setText("Xin chào, " + ongCan.getTen());
        jLabel16.setText(ongCan.getHo() + " " +  ongCan.getTen());
        jLabel17.setText(ongCan.getCapBac());
        
        congAn.setBackground(ClickedColor);
        donVi.setBackground(DefaultColor);
        khuVuc.setBackground(DefaultColor);
        DTPane.add(menuCongan);
        DTPane.add(menuDonvi);
        DTPane.add(menuKhuvuc);
        DTPane.setSelectedFrame(menuCongan);
        menuCongan.setVisible(true);
        
        checkDarkmode();
    }
    
    private void checkDarkmode() {
        if (UIManager.getLookAndFeel().getClass().getName().equals("com.formdev.flatlaf.FlatDarkLaf")) {
                labelDarkmode.setText("Light mode");
                jPanel1.setBackground(new Color(99, 99, 99));
            } else {
                labelDarkmode.setText("Dark mode");
                jPanel1.setBackground(new Color(255, 255, 255));
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DTPane;
    private javax.swing.JPanel congAn;
    private javax.swing.JPanel donVi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel khuVuc;
    private javax.swing.JLabel labelDarkmode;
    private javax.swing.JLabel lableCA;
    private javax.swing.JLabel lableDV;
    private javax.swing.JLabel lableKV;
    private javax.swing.JLabel lableLogout;
    // End of variables declaration//GEN-END:variables
}
